spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-enterprise?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&useSSL=false
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #乱码配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
## redis配置，默认没有密码
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 6000 #5000毫秒
    database: 0  #默认0

#
  # session 存储到 redis，实现分布式 session
  session:
    store-type: redis
    redis:
      namespace: phzx:session
    # 一分钟超时
    timeout: 10


#
#amqconfig:
#  queue:
#    name: messageQueue

security:
    login:
      page: /login.html


server:
  servlet:
    session:
      timeout: 10
  tomcat:
    uri-encoding: UTF-8
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml




